export const LANG_EN_NAME = 'en'; 
export const LANG_EN_TRANS = { 
  'USUÁRIO':'USER', 
  'CONSULTAR':'SEARCH', 
  'Consultar':'Search', 
  'EDITAR':'EDIT', 
  'INSERIR':'INSERIR', 
  'Relatórios':'Reports', 
  'Usuários':'Users', 
  'Cadastros':'Records', 
  'RELATÓRIO':'REPORT', 
  'participantes':'Items', 
  'apontamentos':'Releases', 
  'Permissões':'Permissions', 
  'Grupo de Usuários':'User group', 
  'Administração':'Management', 
  'Dicionário':'Dictionary', 
  'CÓDIGO':'ID', 
 'GRUPO':'GROUP', 
 'BEM VINDO AO SISTEMA':'WELCOME TO THE SYSTEM', 
 'é obrigatório':'is required', 
 'Relatório':'Report', 
 'RELATÓRIO DE':'REPORT OF', 
 'FILTRO RELATÓRIO':'FILTER REPORT', 
 'APONTAMENTO DE TEMPOS':'RELEASE OF TIME', 
 'FILTRO APONTAMENTO':'FILTER RELEASE', 
  'cadastro de':'Registration of', 
  'APONTAMENTO DE TEMPO':'RELEASE OF TIME', 
  'Adicionar':'Add',
  'Gravar':'Save',
  'Cancelar':'Cancel',
  'Excluir':'Delete', 
  'Editar':'Edit', 
  'CAMPOS':'FIELDS', 
  'TOTAL GERAL':'GRAND TOTAL', 
  'Gráficos':'Charts', 
  'Imprimir':'Print', 
  'Voltar':'Back', 
  'PIZZA':'PIE', 
  'LINHAS':'LINES', 
  'BARRAS':'BAR', 
  'DE':'FROM', 
  'ATÉ':'TO', 
  'ENTRAR':'ENTER', 
  'ACESSAR':'ACCESS', 
  'LOGIN':'USER', 
  'SENHA':'PASSWORD', 
 'SISTEMA GERENCIADOR DE MANUTENÇÕES':'SISTEMA GERENCIADOR DE MANUTENÇÕES', 
  'Abertas':'Start', 
  'Ano':'Year', 
  'Ano do Feriado':'Holiday Year', 
  'ANO (ELE)':'', 
  'ANO (MEC)':'', 
  'ANO (OPE)':'', 
  'ANUAL':'ANUAL', 
  'Apontamentos de Manutenção Preventiva':'Preventive Maintenance Notes', 
  'Com essa interface podemos apontar as Manutenções Preventivas conforme o cronograma do dia, apontar se foi feito, na data, e o tempo que levou para apontar. Para os participantes de Manutenção Preventiva temos os participantes do gabarito, que devemos apontar uma a um, informando em qual data foi feito, qual tempo que levou para cada item. Também aqui vamos apontar o tempo que levou cada manutenção da Máquina dentro do Cronograma.':'With this interface we can point Preventive Maintenance according to the schedule of the day, point out if it was done, the date, and the time it took to point. For Preventive Maintenance Items we have the template items, which we must point out one by one, stating on what date it was made, how long it took for each item. Also here we will point out the time taken for each Machine maintenance within the Schedule.', 
  'Apontamentos de Tempo de Solicitação de Manutenção Corretiva':'Corrective Maintenance Request Time Notes', 
  'Nessa interface são apontados os tempos de Manutenção Corretiva das Máquinas.':'This interface shows the corrective maintenance times of the machines.', 
  'Apontamentos de Tempos (Solicitação de Manutenção Corretiva)':'Time Notes (Request for Corrective Maintenance)', 
  'Com essa interface podemos apontar o tempo de trabalho que leva para executar a manutenção corretiva, iniciando cada tarefa, parando, continuando e finalizando':'With this interface we can point out the time it takes to perform corrective maintenance, starting each task, stopping, continuing and ending', 
  'Ativa':'Active', 
  'Máquina está em atividade':'Machine is up and running', 
  'Bairro':'Address Neighborhood', 
  'Barro do Endereço':'Address Neighborhood', 
  'Causa da Manutenção':'Cause of Maintenance', 
  'Nessa tela cadastramos quais são as possíveis causas que levaram o equipamento a manutenção':'In this screen we register what are the possible causes that led the equipment to maintenance', 
  'Causa Manutenção':'Cause Maintenance', 
  'Causa Origem do Problema que gerou a Manutenção':'Cause Source of Issue that generated Maintenance', 
  'Código':'ID', 
  'Código da Causa da Manutenção':'ID Cause of Maintenance', 
  'Código de Integração':'Integration Code', 
  'Código de Integração é usado para cadastrar o código da peça em outro sistema que é integrado ao agenda-esporte':'Integration Code is used to register part code in another system that is integrated with agenda-esporte', 
  'Código Integração':'ID Integration', 
  'Celular':'Cellphone', 
  'Celular de Contato':'Contact cellphone', 
  'Centro de Custo':'Cost Center', 
  'Centro de Custo a qual a máquina pertence para fins financeiros':'Cost Center to which the machine belongs for financial purposes.', 
  'Centro de Custos':'Cost Center', 
  'Chamados':'Called', 
  'Com esta tela podemos criar os chamados de Manutenção Corretiva, os quais serão analisados pelos mecânicos. Podem se transformar em uma Solicitação de Manutenção efetiva ou resolvidos com respostas simples.':'With this screen we can create the so-called Corrective Maintenance, which will be analyzed by mechanics. They can be transformed into an effective Maintenance Request or resolved with simple answers.', 
  'Checar participantes na M.P.':'Check Items on M.P.', 
  'Aqui definimos se a equipe responsável pela M.P. deve ou não checar os subparticipantes da M.P.':'Here we define whether or not the team responsible for M.P. should check M.P. sub-items.', 
  'Cidade':'City', 
  'Cidade do Endereço':'Address City', 
  'Classe da Manutenção':'Maintenance Class', 
  'Qual é a classificação (Classe) que se adapta o Manutenção Corretiva':'What rating (Class) fits Corrective Maintenance', 
  'Classe de Manutenção':'Maintenance Class', 
  'Nessa tela definimos a classificação da manutenção':'In this screen we define the maintenance classification', 
  'Codigo Item Gabarito':'', 
  'Codigo':'', 
  'Conclusão/Observações':'Conclusion', 
  'Conclusão do Chamado':'Call Completion', 
  'Configurações de Cronograma de Máquinas':'Machine Schedule Settings', 
  'Com essa interface podemos cadastrar todas as máquina que terão cronograma fixo durante uma ano determinado, para a realização das manutenções preventivas. Iremos configurar cadas máquina para gerar os cálculos de tempos de manutenção, conforme o gabarito de manutenção (roteiro), dentro de um período, equipe responsável.':'With this interface we can register all machines that will have fixed schedule for a given year, to perform preventive maintenance. We will configure the machine to generate the maintenance time calculations, according to the maintenance template (script), within a period, responsible team.', 
  'Consumo de Energia (Kw/h)':'Energy Consumption (Kw / h)', 
  'Consumo de Energia de Máquina medida em (Kw/h)':'Machine Power Consumption measured in (Kw / h)', 
  'Contato':'Contact', 
  'Contato na Empresa':'Company Contact', 
  'Criticidade':'Criticality', 
  'Qual é a criticidade do Defeito que Gerou a Manutenção':'What is the criticality of the defect that generated the maintenance', 
  'Custo':'Cost of Part Purchase', 
  'Custo Hora Máquina':'Machine Hour Cost', 
  'Qual é o custo da hora de uma máquina (mensurar custo de produção e ônus de máquina parada)':'What is the hourly cost of a machine (measuring production cost and downtime)', 
  'Data':'Date', 
  'Data do Feriado':'Date of Holiday', 
  'Data Anual':'Annual Date', 
  'Data que será a manutenção anual':'Date that will be the annual maintenance', 
  'Data Emissão':'Issue Date', 
  'Data de emissão da Nota Fiscal':'Date of Invoice Issue', 
  'Data Inicial (dia/mês/Semana)':'Start Date (day / month / week)', 
  'Data a qual vai começar a gerar o cronograma dentro de um ano para as manutenções diárias, semanais e mensais':'Date which will start generating schedule within one year for daily, weekly and monthly maintenance', 
  'Data Inicial (Semestral)':'Start Date (Half Year)', 
  'Data inicial para as manutenções semestrais (2 datas) dentro do ano ':'Starting date for semiannual maintenance (2 dates) within the year', 
  'Data Inicial (Trimestral)':'Start Date (Quarterly)', 
  'Data inicial para as manutenções trimestrais dentro de uma ano (4 datas)':'Starting date for quarterly maintenance within one year (4 dates)', 
  'Data Limite (Dias) Antecipação':'Deadline (Days) Anticipation', 
  'Data Limite para antecipação da Manutenção Preventiva, definidas em dias conforme configuração no cadastro de período.':'Deadline for anticipation of Preventive Maintenance, defined in days as configured in the period record.', 
  'Data Limite (Dias) Postergação':'Deadline (Days) Postponement', 
  'Data Limite para postergação após a Data Prevista da Manutenção Preventiva. Definida em dias conforme o Cadastro de Períodos.':'Deadline for postponement after Expected Preventive Maintenance Date. Defined in days according to the Period Register.', 
  'Data Prevista':'Expected date', 
  'Data de Previsão de Conclusão da Manutenção':'Maintenance Completion Forecast Date', 
  'Data/Hora':'Date/Hour', 
  'Data e Hora da Abertura do Chamado':'Call Opening Date and Time', 
  'Data/Hora Chamado':'Date/Hour Chamado', 
  'Data e Hora na qual foi feito o Chamado de Manutenção Corretiva':'Date and Time Corrective Maintenance Call Was Made', 
  'Data/Hora da Conclusão':'Date/Hour Conclusion', 
  'Data e Hora da Conclusão do Chamado':'Call End Date and Time', 
  'Data/Hora Final':'Date/Hour Finally', 
  'Data e Hora Final do Apontamento de Tempo':'Time Point End Date and Time', 
  'Data/Hora Inicial':'Date/Hour Start', 
  'Data e Hora que iniciou o apontamento de tempo':'Table showing the Preventive Maintenance Times Performed', 
  'Data/Hora Solução':'', 
  'Data e Hora da Solução do Chamado':'Call Resolution Date and Time', 
  'Descrição':'Description', 
  'Descrição da Causa da Manutenção':'Description Cause of Maintenance', 
  'DIA (ELE)':'DIA (ELE)', 
  'DIA (MEC)':'DIA (MEC)', 
  'Dia de Término na Semana':'Week End Day', 
  'Dia da Semana em que a Máquina encerra as atividades':'Day of the Week when the Machine Ends Activities', 
  'Dia Inicio Semana':'Day Start Week', 
  'Em que dia da semana a Máquina começa a Trabalhar':'What day of the week does the machine start working', 
  'Dias de Tolerância (M.P.) ':'Tolerance Days (M.P.)', 
  'Dias de Tolerância para realização da M.P. conforme o calendário, para antecipação da M.P. ou postergação.':'Days of Tolerance to perform M.P. according to schedule, for anticipation of M.P. or postponement.', 
  'Dias por Semana':'Days a Week', 
  'Quantos dias dentro de uma semana a máquina funciona dentro da empresa de 1 a 7':'How many days within a week does the machine run from 1 to 7', 
  'DIÁRIA':'DIÁRIA', 
  'E-mail':'E-mail', 
  'E-mail de Contato':'E-mail Contact', 
  'Encerradas':'End', 
  'Endereço':'', 
  'Endereço do usuario':'Supplier Address', 
  'Equipe Responsável':'Responsible team', 
  'Equipe Responsável pela Manutenção Corretiva':'Team Responsible for Corrective Maintenance', 
  'Equipe Responsável pela M.P.':'Team Responsible for M.P.', 
  'Nessa tela vamos cadastrar as equipes responsáveis pela execução da Manutenção Preventiva':'In this screen we will register the teams responsible for performing Preventive Maintenance', 
  'Estado':'State', 
  'Estado do Endereço':'Address State', 
  'Estoque':'Stock', 
  'Quantidade de Peças existente no estoque da empresa':'Number of Parts in Company Stock', 
  'Estoque Mínimo':'Minimum Stock', 
  'Qual é o estoque mínimo da peças, quando atingido deve ser incluído no relatório de estoque mínimo que gera um pedido de compra':'What is the minimum stock of parts when reached should be included in the minimum stock report that generates a purchase order', 
  'Feriados':'Holidays', 
  'Cadastro de Feriados dentro de uma ano para efeitos de geração de Cronograma de Manutenção Preventiva ':'Holiday Registration within one year for the purpose of Preventive Maintenance Schedule generation', 
  'usuarios':'Providers', 
  'usuarios de Peças para manutenção corretiva das máquinas':'Spare Parts for Machine Maintenance Suppliers', 
  'Gabarito de Manutenção Preventiva':'Preventive Maintenance Template', 
  'Gabarito de Manutenção Preventiva é um roteiro a ser seguido para as Manutenções Preventivas, Junto com seus participantes a server checados quando dentro do cronograma de Manutenção Preventiva ela é realizada por um profissional um check list e disposto para verificar se foi feito na data certa e dentro do tempo estimado. O Gabarito é vinculado a uma máquina, para um determinado período de manutenção e destinado a uma equipe responsável pela manutenção':'Preventive Maintenance Template is a roadmap to follow for Preventive Maintenance, along with your server items checked when within the Preventive Maintenance schedule it is performed by a professional checklist and willing to check if it was done on time and on time. of the estimated time. The Template is linked to a machine for a certain maintenance period and is intended for a maintenance team.', 
  'Gabarito participantes':'Feedback Items', 
  'Aqui está o roteiro a ser seguido em forma de checklist mostrando a equipe responsável cada item que deve ser aplicado o tempo relevante e se foi feito ou não.':'Here is the roadmap to be followed in checklist showing the responsible team each item that should be applied the relevant time and whether it was done or not.', 
  'Geral Anual (Mec)':'', 
  'Gerar Anual (Ele)':'', 
  'Gerar Anual (Ope)':'', 
  'Gerar Semestral (Ele)':'', 
  'Gerar Semestral (Mec)':'', 
  'Gerar Semestral (Ope)':'', 
  'Gerar Trimestral (Ele)':'', 
  'Gerar Trimestral (Mec)':'', 
  'Gerar Trimestral (Ope)':'', 
  'Hora Inicio Dia':'Time Start Day', 
  'Hora Término Dia':'Time End Day', 
  'Hora em que a máquina encerra as atividades no dia':'Time when the machine shuts down on the day', 
  'Horas Dia':'Day/Hour', 
  'Quantas horas por dia a Máquina trabalha':'How many hours per day does the machine work?', 
  'Imagem':'Image', 
  'Imagem/Foto da máquina':'Image/photo of Machine', 
  'Imagem/foto':'Image/Photo', 
  'Imagem/Foto da Peça':'Image/Photo of Part', 
  'participantes da Nota Fiscal':'Items of Invoice', 
  'participantes da Nota Fiscal de Entrada de Peças':'Incoming Invoice Items', 
  'participantes de Manutenção Preventiva Realizada':'Preventive Maintenance Items Performed', 
  'Localização':'Location', 
  'Localização Física no Estoque da Peça':'Physical Location in Part Stock', 
  'Manutenção Preventiva Prevista (Cronograma)':'Preventive Preventive Maintenance (Schedule)', 
  'Cronograma de Manutenções Preventivas Realizadas':'Schedule of Preventive Maintenance Performed', 
  'Manutenção Preventiva Realizada (Tempos)':'Preventive Maintenance Performed (Times)', 
  'Tabela onde são apontados os Tempos de Manutenção Preventiva Realizada':'Table showing the Preventive Maintenance Times Performed', 
  'Manutenções Preventivas Realizadas':'Preventive Maintenance Performed', 
  'Esta Tela traz todas as Manutenções Preventivas Realizadas. Estes lançamentos são gerados pela tela de apontamento de Realizadas.':'This Screen displays all Preventive Maintenance Performed. These postings are generated by the Achievement pointing screen.', 
  'Máquina':'Machine', 
  'Máquina de Gabarito de Manutenção Preventiva':'Machine of Preventive Maintenance Template', 
  'Máquinas':'Machines', 
  'Nessa tela vamos cadastrar todas as máquinas da empresa, que estarão no roteiro e cronograma de Manutenções Preventivas e Corretivas':'In this screen we will register all the machines of the company, which will be in the script and schedule of Preventive and Corrective Maintenance', 
  'MCA':'MCA', 
  'MENSAL':'MENSAL', 
  'MENSAL (ELE)':'', 
  'MENSAL (MEC)':'', 
  'Motivos de Espera':'Reasons for Waiting', 
  'Qual é o motivo que pode atrasar a realização da Manutenção':'What may delay the maintenance', 
  'MPO':'MPO', 
  'MPO (DIA/SEMANA/MES)':'', 
  'Número':'Number', 
  'Número de Endereço':'Address Number', 
  'Número da Nota Fiscal':'Number Invoice', 
  'Número da Nota Fiscal emitida pelo usuario':'Invoice Number issued by Supplier', 
  'Número de Série':'Serial number', 
  'Número de Série da Máquina':'Machine Serial Number', 
  'Nome':'Name', 
  'Nome da Peça':'Part Name', 
  'Nota Fiscal de Entrada':'Invoice', 
  'Nessa tela vamos cadastrar as Notas Fiscais de Entrada de Peças emitidas pelos usuarios, Nessa tela é incrementado o estoque de Peças na Empresa':'In this screen we will register the Invoices of Parts Entry issued by the Suppliers, In this screen is increased the inventory of Parts in the Company.', 
  'Obrigatório Selecionar Subconjunto':'Required Select Subset', 
  'Especifica se a equipe e obrigada a selecionar o subconjunto (quando as máquinas forem subdividias em subconjuntos)':'Especifica se a equipe e obrigada a selecionar o subconjunto (quando as máquinas forem subdividias em subconjuntos)', 
  'Observações':'Comments', 
  'Comentários gerais sobre o usuario':'General Comments on the Supplier', 
  'Observações/Conclusão':'Conclusion', 
  'O Solicitante muda o status para concluído e descreve a conclusão':'Requester changes status to completed and describes completion', 
  'Ociosa':'Idle', 
  'Esta máquina esta ociosa ou em funcionamento':'This machine is idle or running', 
  'Onde?':'Where?', 
  'Onde foi o defeito na Máquina ou no SubConjunto':'Where was the defect in the Machine or Subset', 
  'País':'Country', 
  'País do Endereço':'Address Country', 
  'Parou a Produção no Atendimento':'Stopped Service Production', 
  'Parou a produção no Atendimento':'Stopped Service Production', 
  'Parou a Produção?':'Parou a Produção?', 
  'Está com a produção parada devida ao defeito que gerou a Manutenção Corretiva?':'Is production stopped due to the defect that generated Corrective Maintenance?', 
  'Peça':'Part', 
  'Peça Solicitada para o setor de Compras':'Purchase Request Items', 
  'Peça Nova':'New Part', 
  'A peça adquira é nova ou reutilizada':'The part you purchase is new or reused', 
  'Peças':'Parts', 
  'Aqui nos vamos cadastrar todas as peças usadas na manutenção corretiva dos equipamentos, através desse cadastro de peças iremos usar nos cadastro de Nota Fiscal, Pedidos de Peças, etc.':'Here we will register all parts used in the corrective maintenance of equipment, through this parts register we will use in the invoice register, Parts Requests, etc.', 
  'Peço':'Price', 
  'Preço da Peça qual foi comprado a peça':'Part Price which part was purchased', 
  'Período':'Period', 
  'Periodicidade que vai ser aplicada a Manutenção Preventiva':'Frequency that will be applied to Preventive Maintenance', 
  'Períodos M.P.':'Preventive Maintenance Periods', 
  'Nessa tela cadastramos os possíveis períodos que são feitas as Manutenções Preventivas':'In this screen we register the possible periods that are made Preventive Maintenance', 
  'Procedimento':'Procedure', 
  'Procedimento a ser seguido':'Procedure to follow', 
  'QUADRIMESTRAL':'QUADRIMESTRAL', 
  'Quantidade':'Amount', 
  'Quantidade Solicitada':'Ordered Quantity', 
  'Que Fazer':'What to do', 
  'Que Fazer no Item':'What to do in Item', 
  'Requisição':'Number of Request', 
  'Número da Requisição de Compra que gerou a Nota Fiscal de Peças':'Purchase Requisition Number that generated the Invoice for Parts', 
  'Requisições de Peças':'Parts Requests', 
  'Com esta tela podemos fazer as requisições de peças ao almoxarifado, reservando assim a peça no estoque para uso da manutenção corretiva do equipamento.':'With this screen we can order parts from the warehouse, thus reserving the part in stock for corrective equipment maintenance.', 
  'S.M.C. por Máquinas (Abertas x Encerradas) no Período':'S.M.C. by Machines (Open vs. Closed) in the Period', 
  'Símbolo':'Symbol', 
  'Qual símbolo (abreviação) deve ser associado ao Período':'Which symbol (abbreviation) should be associated with the Period', 
  'SEMANAL':'SEMANAL', 
  'SEMANAL (ELE)':'', 
  'SEMANAL (MEC)':'', 
  'SEMESTRAL':'SEMESTRAL', 
  'SEMESTRAL (ELE)':'', 
  'SEMESTRAL (MEC)':'', 
  'SEMESTRAL (OPE)':'', 
  'Sequência':'Sequence ID', 
  'Sequencia de participantes de Solicitação Compras':'Sequence of Purchase Request Items', 
  'Sequência do Item':'Sequence of Item', 
  'Sequência do Item da Nota Fiscal de Entrada':'Invoice Item Sequence', 
  'Setor':'Sector', 
  'Setor em que a máquina pertence':'Setor em que a máquina pertence', 
  'Setores':'Sectors', 
  'Nessa tela vamos cadastrar os Setores da Empresa':'In this screen we will register the Company Sectors', 
  //'SISTEMA GERENCIADOR DE MANUTENÇÕES':'MAINTENANCE MANAGEMENT SYSTEM', 
  'O agenda-esporte, SISTEMA GERENCIADOR DE MANUTENÇÕES, TRATA DA GERENCIA DAS MANUTENÇÕES PERIÓDICAS DOS EQUIPAMENTOS DENTRO DA EMPRESA, MANUTENÇÕES PREVENTIVAS/CORRETIVAS QUE SEGUE UM CRONOGRAMA DIÁRIOS, SEMANAL, MENSAL, TRIMESTRAL, QUADRIMESTRAL, SEMESTRAL E ANUAL. TENDO COMO BASE UM CHECKLIST PARA participantes ONDE É FEITO A CHECAGEM, REGISTRADO O TEMPO PREVISTO E REAL DE CADA ITEM E SUBITEM, CONTAMOS COM APONTAMENTOS DE TEMPO PARA CADA MANUTENÇÃO. TAMBÉM CONTAMOS COM O SUPORTE A CHAMADOS DE PARADAS DE MÁQUINAS, SOLICITAÇÃO DE MANUTENÇÕES E APONTAMENTOS DE TEMPOS JUNTO AOS MECÂNICOS. CONTROLE DE ESTOQUE DE PEÇAS E SOLICITAÇÕES DE PEÇAS E COMPRAS DE PEÇAS.':'The agenda-esporte, MAINTENANCE MANAGEMENT SYSTEM, TREATY ON PERIODIC MAINTENANCE MANAGEMENT INSIDE THE COMPANY, PREVENTIVE / CORRECTIVE MAINTENANCE FOLLOWING A DAILY, WEEKLY, MONTHLY, QUARTERLY, EVERY-YEAR-PERIODAL SCHEDULE. BASED ON AN ITEM CHECKLIST WHERE CHECKING IS DONE, REGISTERED THE FORECAST AND REAL TIME OF EACH ITEM AND SUBMIT, WE HAVE TIME POINTS FOR EACH MAINTENANCE. WE ALSO COUNT ON SUPPORT FOR CALLING MACHINES, REQUESTING MAINTENANCE AND TIMING WITH MECHANICS. PARTS STOCK CONTROL AND PARTS RE', 
  'Solicitação de Compras':'Shopping request', 
  'Nesta tela vamos cadastrar todas as solicitações de compras enviadas ao setor de compras pode ou não ser oriunda de uma Solicitação de Manutenção Corretiva':'In this screen we will record all purchase requests sent to the purchasing department may or may not come from a Corrective Maintenance Request', 
  'Solicitação de Manutenção Corretiva':'Machine for which parts are intended', 
  'Solicitação ':'Solicitação de Manutenção Corretiva a qual as Peças estão vinculadas', 
  'Solicitações de Manutenção Corretiva':'Corrective Maintenance Requests', 
  'Nesta tela devemos cadastrar e trabalhar todos as solicitações de manutenção, pois de uma chamado de manutenção gera-se a Solicitação de Manutenção Corretiva quando efetivamente for necessário executar uma manutenção corretiva. Com esses registros podemos apontar tempos de manutenção, quais mecânicos estão trabalho na manutenção, tempos de horas trabalhadas e de hora parada de máquina, peças utilizadas na manutenção, requisições de peças ao almoxarifado. etc. ':'In this screen we must register and work all maintenance requests, because a maintenance call generates the Corrective Maintenance Request when it is really necessary to perform a corrective maintenance. With these records we can point out maintenance times, which mechanics are working in maintenance, hours worked and machine downtime, parts used in maintenance, parts requests to the warehouse. etc.', 
  'Solicitante':'Current_Date', 
  'Usuário Solicitante  (Quem abriu o Chamado)':'Requesting User (Who opened the Call)', 
  'Solução/Serviços':'', 
  'Descrição da Solução e Serviços executados':'Solution Description and Services performed', 
  'Status':'Status', 
  'Status da Manutenção':'mechanical', 
  'Em que estágio anda a Manutenção Aberta, Iniciada, Em Andamento, Finalizada, etc.':'At what stage is Maintenance Open, Started, In Progress, Finished, etc.', 
  'Status de S.M.C.':'', 
  'SubConjunto':'SubSet', 
  'SubConjunto da Máquina':'SubSet of Machine', 
  'SubTotal':'SubTotal', 
  'SubTotal do Item da Nota Fiscal':'Invoice Item SubTotal', 
  'Telefone':'Phone', 
  'Telefone de Contato':'Phone of Contact', 
  'Tempo':'Time', 
  'Tempo Calculado (minutos)':'Calculated Time (minutes)', 
  'Tempo Estimado (minutos)':'Estimated time (minutes)', 
  'Tempo Estimado do Item em Minutos':'Estimated time in Item in minutes', 
  'Tempo Previsto':'Expected Time', 
  'Tempo Previsto para conclusão da Manutenção':'Expected Time to Complete Maintenance', 
  'Tempo Realizado (Minutos)':'Accomplished Time (Minutes)', 
  'Tempo que realizou a Manutenção Preventiva':'Time that performed Preventive Maintenance', 
  'Tempo Total':'Total Time', 
  'Tempo Total de Manutenção Preventiva para a Máquina':'Total Preventive Machine Maintenance Time', 
  'Tipo de Manutenção':'Maintenance Type', 
  'Tipo de Manutenção a ser aplicada na Solicitação':'Type of Maintenance to apply on Request', 
  'Tipo Manutenção':'Maintenance Type', 
  'Equipe responsável pela M.P. e o Tipo de Manutenção Realizada':'Team responsible for M.P. and Type of Maintenance Performed', 
  'Total':'Total', 
  'Valor Total da Nota Fiscal':'Total Amount of Invoice', 
  'Total Abertas':'Total Start', 
  'Total de S.M.C. por Máquina (Encerradas x Total ) no Período':'Total S.M.C. per Machine Period', 
  'Total de S.M.C. por Máquinas (Abertas x Total) no Período':'Total S.M.C. by Machines (Open x Total) in Period', 
  'TRIMESTRAL':'TRIMESTRAL', 
  'TRIMESTRAL (ELE)':'', 
  'TRIMESTRAL (MEC)':'', 
  'TRIMESTRAL (OPE)':'', 
  'TTDPA':'TTDPA', 
  'TTMP':'TTMP', 
  'TTMP (ELE)':'TTMP (ELE)', 
  'TTMP (MEC)':'TTMP (MEC)', 
  'TTMP (MEC/ELE)':'TTMP (MEC/ELE)', 
  'Unidade':'Unit', 
  'Unidade da Peça':'Unit of Part', 
};
