export const LANG_BR_NAME = 'br'; 
export const LANG_BR_TRANS = { 
  'USUÁRIO':'USUÁRIO', 
  'CONSULTAR':'CONSULTAR', 
  'Consultar':'Consultar', 
  'EDITAR':'EDITAR', 
  'INSERIR':'INSERIR', 
  'Relatórios':'Relatórios', 
  'Usuários':'Usuários', 
  'Cadastros':'Cadastros', 
  'RELATÓRIO':'RELATÓRIO', 
  'participantes':'participantes', 
  'apontamentos':'apontamentos', 
  'Permissões':'Permissões', 
  'Grupo de Usuários':'Grupo de Usuários', 
  'Administração':'Administração', 
  'Dicionário':'Dicionário', 
  'CÓDIGO':'CÓDIGO', 
 'GRUPO':'GRUPO', 
 'BEM VINDO AO SISTEMA':'BEM VINDO AO SISTEMA', 
 'é obrigatório':'é obrigatório', 
 'Relatório':'Relatório', 
 'RELATÓRIO DE':'RELATÓRIO DE', 
 'FILTRO RELATÓRIO':'FILTRO RELATÓRIOS', 
 'FILTRO APONTAMENTO':'FILTRO APONTAMENTO', 
  'cadastro de':'cadastro de', 
  'APONTAMENTO DE TEMPO':'APONTAMENTO DE TEMPO', 
  'Adicionar':'Adicionar',
  'Gravar':'Gravar',
  'Cancelar':'Cancelar',
  'Excluir':'Excluir', 
  'Editar':'Editar', 
  'CAMPOS':'CAMPOS', 
  'TOTAL GERAL':'TOTAL GERAL', 
  'Gráficos':'Gráficos', 
  'Imprimir':'Imprimir', 
  'Voltar':'Voltar', 
  'PIZZA':'PIZZA', 
  'LINHAS':'LINHAS', 
  'BARRAS':'BARRAS', 
  'DE':'DE', 
  'ATÉ':'ATÉ', 
  'ENTRAR':'ENTRAR', 
  'ACESSAR':'ACESSAR', 
  'LOGIN':'LOGIN', 
  'SENHA':'SENHA', 
 'SISTEMA GERENCIADOR DE MANUTENÇÕES':'SISTEMA GERENCIADOR DE MANUTENÇÕES', 
  'Abertas':'Abertas', 
  'Ano':'Ano', 
  'Ano do Feriado':'Ano do Feriado', 
  'ANO (ELE)':'ANO (ELE)', 
  'ANO (MEC)':'ANO (MEC)', 
  'ANO (OPE)':'ANO (OPE)', 
  'ANUAL':'ANUAL', 
  'Apontamentos de Manutenção Preventiva':'Apontamentos de Manutenção Preventiva', 
  'Com essa interface podemos apontar as Manutenções Preventivas conforme o cronograma do dia, apontar se foi feito, na data, e o tempo que levou para apontar. Para os participantes de Manutenção Preventiva temos os participantes do gabarito, que devemos apontar uma a um, informando em qual data foi feito, qual tempo que levou para cada item. Também aqui vamos apontar o tempo que levou cada manutenção da Máquina dentro do Cronograma.':'Com essa interface podemos apontar as Manutenções Preventivas conforme o cronograma do dia, apontar se foi feito, na data, e o tempo que levou para apontar. Para os participantes de Manutenção Preventiva temos os participantes do gabarito, que devemos apontar uma a um, informando em qual data foi feito, qual tempo que levou para cada item. Também aqui vamos apontar o tempo que levou cada manutenção da Máquina dentro do Cronograma.', 
  'Apontamentos de Tempo de Solicitação de Manutenção Corretiva':'Apontamentos de Tempo de Solicitação de Manutenção Corretiva', 
  'Nessa interface são apontados os tempos de Manutenção Corretiva das Máquinas.':'Nessa interface são apontados os tempos de Manutenção Corretiva das Máquinas.', 
  'Apontamentos de Tempos (Solicitação de Manutenção Corretiva)':'Apontamentos de Tempos (Solicitação de Manutenção Corretiva)', 
  'Com essa interface podemos apontar o tempo de trabalho que leva para executar a manutenção corretiva, iniciando cada tarefa, parando, continuando e finalizando':'Com essa interface podemos apontar o tempo de trabalho que leva para executar a manutenção corretiva, iniciando cada tarefa, parando, continuando e finalizando', 
  'Ativa':'Ativa', 
  'Máquina está em atividade':'Máquina está em atividade', 
  'Bairro':'Bairro', 
  'Barro do Endereço':'Barro do Endereço', 
  'Causa da Manutenção':'Causa da Manutenção', 
  'Nessa tela cadastramos quais são as possíveis causas que levaram o equipamento a manutenção':'Nessa tela cadastramos quais são as possíveis causas que levaram o equipamento a manutenção', 
  'Causa Manutenção':'Causa Manutenção', 
  'Causa Origem do Problema que gerou a Manutenção':'Causa Origem do Problema que gerou a Manutenção', 
  'Código':'Código', 
  'Código da Causa da Manutenção':'Código da Causa da Manutenção', 
  'Código de Integração':'Código de Integração', 
  'Código de Integração é usado para cadastrar o código da peça em outro sistema que é integrado ao agenda-esporte':'Código de Integração é usado para cadastrar o código da peça em outro sistema que é integrado ao agenda-esporte', 
  'Código Integração':'Código Integração', 
  'Celular':'Celular', 
  'Celular de Contato':'Celular de Contato', 
  'Centro de Custo':'Centro de Custo', 
  'Centro de Custo a qual a máquina pertence para fins financeiros':'Centro de Custo a qual a máquina pertence para fins financeiros', 
  'Centro de Custos':'Centro de Custos', 
  'Chamados':'Chamados', 
  'Com esta tela podemos criar os chamados de Manutenção Corretiva, os quais serão analisados pelos mecânicos. Podem se transformar em uma Solicitação de Manutenção efetiva ou resolvidos com respostas simples.':'Com esta tela podemos criar os chamados de Manutenção Corretiva, os quais serão analisados pelos mecânicos. Podem se transformar em uma Solicitação de Manutenção efetiva ou resolvidos com respostas simples.', 
  'Checar participantes na M.P.':'Checar participantes na M.P.', 
  'Aqui definimos se a equipe responsável pela M.P. deve ou não checar os subparticipantes da M.P.':'Aqui definimos se a equipe responsável pela M.P. deve ou não checar os subparticipantes da M.P.', 
  'Cidade':'Cidade', 
  'Cidade do Endereço':'Cidade do Endereço', 
  'Classe da Manutenção':'Classe da Manutenção', 
  'Qual é a classificação (Classe) que se adapta o Manutenção Corretiva':'Qual é a classificação (Classe) que se adapta o Manutenção Corretiva', 
  'Classe de Manutenção':'Classe de Manutenção', 
  'Nessa tela definimos a classificação da manutenção':'Nessa tela definimos a classificação da manutenção', 
  'Codigo Item Gabarito':'Codigo Item Gabarito', 
  'Codigo':'Codigo', 
  'Conclusão/Observações':'Conclusão/Observações', 
  'Conclusão do Chamado':'Conclusão do Chamado', 
  'Configurações de Cronograma de Máquinas':'Configurações de Cronograma de Máquinas', 
  'Com essa interface podemos cadastrar todas as máquina que terão cronograma fixo durante uma ano determinado, para a realização das manutenções preventivas. Iremos configurar cadas máquina para gerar os cálculos de tempos de manutenção, conforme o gabarito de manutenção (roteiro), dentro de um período, equipe responsável.':'Com essa interface podemos cadastrar todas as máquina que terão cronograma fixo durante uma ano determinado, para a realização das manutenções preventivas. Iremos configurar cadas máquina para gerar os cálculos de tempos de manutenção, conforme o gabarito de manutenção (roteiro), dentro de um período, equipe responsável.', 
  'Consumo de Energia (Kw/h)':'Consumo de Energia (Kw/h)', 
  'Consumo de Energia de Máquina medida em (Kw/h)':'Consumo de Energia de Máquina medida em (Kw/h)', 
  'Contato':'Contato', 
  'Contato na Empresa':'Contato na Empresa', 
  'Criticidade':'Criticidade', 
  'Qual é a criticidade do Defeito que Gerou a Manutenção':'Qual é a criticidade do Defeito que Gerou a Manutenção', 
  'Custo':'Custo', 
  'Custo Hora Máquina':'Custo Hora Máquina', 
  'Qual é o custo da hora de uma máquina (mensurar custo de produção e ônus de máquina parada)':'Qual é o custo da hora de uma máquina (mensurar custo de produção e ônus de máquina parada)', 
  'Data':'Data', 
  'Data do Feriado':'Data do Feriado', 
  'Data Anual':'Data Anual', 
  'Data que será a manutenção anual':'Data que será a manutenção anual', 
  'Data Emissão':'Data Emissão', 
  'Data de emissão da Nota Fiscal':'Data de emissão da Nota Fiscal', 
  'Data Inicial (dia/mês/Semana)':'Data Inicial (dia/mês/Semana)', 
  'Data a qual vai começar a gerar o cronograma dentro de um ano para as manutenções diárias, semanais e mensais':'Data a qual vai começar a gerar o cronograma dentro de um ano para as manutenções diárias, semanais e mensais', 
  'Data Inicial (Semestral)':'Data Inicial (Semestral)', 
  'Data inicial para as manutenções semestrais (2 datas) dentro do ano ':'Data inicial para as manutenções semestrais (2 datas) dentro do ano ', 
  'Data Inicial (Trimestral)':'Data Inicial (Trimestral)', 
  'Data inicial para as manutenções trimestrais dentro de uma ano (4 datas)':'Data inicial para as manutenções trimestrais dentro de uma ano (4 datas)', 
  'Data Limite (Dias) Antecipação':'Data Limite (Dias) Antecipação', 
  'Data Limite para antecipação da Manutenção Preventiva, definidas em dias conforme configuração no cadastro de período.':'Data Limite para antecipação da Manutenção Preventiva, definidas em dias conforme configuração no cadastro de período.', 
  'Data Limite (Dias) Postergação':'Data Limite (Dias) Postergação', 
  'Data Limite para postergação após a Data Prevista da Manutenção Preventiva. Definida em dias conforme o Cadastro de Períodos.':'Data Limite para postergação após a Data Prevista da Manutenção Preventiva. Definida em dias conforme o Cadastro de Períodos.', 
  'Data Prevista':'Data Prevista', 
  'Data de Previsão de Conclusão da Manutenção':'Data de Previsão de Conclusão da Manutenção', 
  'Data/Hora':'Data/Hora', 
  'Data e Hora da Abertura do Chamado':'Data e Hora da Abertura do Chamado', 
  'Data/Hora Chamado':'Data/Hora Chamado', 
  'Data e Hora na qual foi feito o Chamado de Manutenção Corretiva':'Data e Hora na qual foi feito o Chamado de Manutenção Corretiva', 
  'Data/Hora da Conclusão':'Data/Hora da Conclusão', 
  'Data e Hora da Conclusão do Chamado':'Data e Hora da Conclusão do Chamado', 
  'Data/Hora Final':'Data/Hora Final', 
  'Data e Hora Final do Apontamento de Tempo':'Data e Hora Final do Apontamento de Tempo', 
  'Data/Hora Inicial':'Data/Hora Inicial', 
  'Data e Hora que iniciou o apontamento de tempo':'Data e Hora que iniciou o apontamento de tempo', 
  'Data/Hora Solução':'Data/Hora Solução', 
  'Data e Hora da Solução do Chamado':'Data e Hora da Solução do Chamado', 
  'Descrição':'Descrição', 
  'Descrição da Causa da Manutenção':'Descrição da Causa da Manutenção', 
  'DIA (ELE)':'DIA (ELE)', 
  'DIA (MEC)':'DIA (MEC)', 
  'Dia de Término na Semana':'Dia de Término na Semana', 
  'Dia da Semana em que a Máquina encerra as atividades':'Dia da Semana em que a Máquina encerra as atividades', 
  'Dia Inicio Semana':'Dia Inicio Semana', 
  'Em que dia da semana a Máquina começa a Trabalhar':'Em que dia da semana a Máquina começa a Trabalhar', 
  'Dias de Tolerância (M.P.) ':'Dias de Tolerância (M.P.) ', 
  'Dias de Tolerância para realização da M.P. conforme o calendário, para antecipação da M.P. ou postergação.':'Dias de Tolerância para realização da M.P. conforme o calendário, para antecipação da M.P. ou postergação.', 
  'Dias por Semana':'Dias por Semana', 
  'Quantos dias dentro de uma semana a máquina funciona dentro da empresa de 1 a 7':'Quantos dias dentro de uma semana a máquina funciona dentro da empresa de 1 a 7', 
  'DIÁRIA':'DIÁRIA', 
  'E-mail':'E-mail', 
  'E-mail de Contato':'E-mail de Contato', 
  'Encerradas':'Encerradas', 
  'Endereço':'Endereço', 
  'Endereço do usuario':'Endereço do usuario', 
  'Equipe Responsável':'Equipe Responsável', 
  'Equipe Responsável pela Manutenção Corretiva':'Equipe Responsável pela Manutenção Corretiva', 
  'Equipe Responsável pela M.P.':'Equipe Responsável pela M.P.', 
  'Nessa tela vamos cadastrar as equipes responsáveis pela execução da Manutenção Preventiva':'Nessa tela vamos cadastrar as equipes responsáveis pela execução da Manutenção Preventiva', 
  'Estado':'Estado', 
  'Estado do Endereço':'Estado do Endereço', 
  'Estoque':'Estoque', 
  'Quantidade de Peças existente no estoque da empresa':'Quantidade de Peças existente no estoque da empresa', 
  'Estoque Mínimo':'Estoque Mínimo', 
  'Qual é o estoque mínimo da peças, quando atingido deve ser incluído no relatório de estoque mínimo que gera um pedido de compra':'Qual é o estoque mínimo da peças, quando atingido deve ser incluído no relatório de estoque mínimo que gera um pedido de compra', 
  'Feriados':'Feriados', 
  'Cadastro de Feriados dentro de uma ano para efeitos de geração de Cronograma de Manutenção Preventiva ':'Cadastro de Feriados dentro de uma ano para efeitos de geração de Cronograma de Manutenção Preventiva ', 
  'usuarios':'usuarios', 
  'usuarios de Peças para manutenção corretiva das máquinas':'usuarios de Peças para manutenção corretiva das máquinas', 
  'Gabarito de Manutenção Preventiva':'Gabarito de Manutenção Preventiva', 
  'Gabarito de Manutenção Preventiva é um roteiro a ser seguido para as Manutenções Preventivas, Junto com seus participantes a server checados quando dentro do cronograma de Manutenção Preventiva ela é realizada por um profissional um check list e disposto para verificar se foi feito na data certa e dentro do tempo estimado. O Gabarito é vinculado a uma máquina, para um determinado período de manutenção e destinado a uma equipe responsável pela manutenção':'Gabarito de Manutenção Preventiva é um roteiro a ser seguido para as Manutenções Preventivas, Junto com seus participantes a server checados quando dentro do cronograma de Manutenção Preventiva ela é realizada por um profissional um check list e disposto para verificar se foi feito na data certa e dentro do tempo estimado. O Gabarito é vinculado a uma máquina, para um determinado período de manutenção e destinado a uma equipe responsável pela manutenção', 
  'Gabarito participantes':'Gabarito participantes', 
  'Aqui está o roteiro a ser seguido em forma de checklist mostrando a equipe responsável cada item que deve ser aplicado o tempo relevante e se foi feito ou não.':'Aqui está o roteiro a ser seguido em forma de checklist mostrando a equipe responsável cada item que deve ser aplicado o tempo relevante e se foi feito ou não.', 
  'Geral Anual (Mec)':'Geral Anual (Mec)', 
  'Gerar Anual (Ele)':'Gerar Anual (Ele)', 
  'Gerar Anual (Ope)':'Gerar Anual (Ope)', 
  'Gerar Semestral (Ele)':'Gerar Semestral (Ele)', 
  'Gerar Semestral (Mec)':'Gerar Semestral (Mec)', 
  'Gerar Semestral (Ope)':'Gerar Semestral (Ope)', 
  'Gerar Trimestral (Ele)':'Gerar Trimestral (Ele)', 
  'Gerar Trimestral (Mec)':'Gerar Trimestral (Mec)', 
  'Gerar Trimestral (Ope)':'Gerar Trimestral (Ope)', 
  'Hora Inicio Dia':'Hora Inicio Dia', 
  'Hora Término Dia':'Hora Término Dia', 
  'Hora em que a máquina encerra as atividades no dia':'Hora em que a máquina encerra as atividades no dia', 
  'Horas Dia':'Horas Dia', 
  'Quantas horas por dia a Máquina trabalha':'Quantas horas por dia a Máquina trabalha', 
  'Imagem':'Imagem', 
  'Imagem/Foto da máquina':'Imagem/Foto da máquina', 
  'Imagem/foto':'Imagem/foto', 
  'Imagem/Foto da Peça':'Imagem/Foto da Peça', 
  'participantes da Nota Fiscal':'participantes da Nota Fiscal', 
  'participantes da Nota Fiscal de Entrada de Peças':'participantes da Nota Fiscal de Entrada de Peças', 
  'participantes de Manutenção Preventiva Realizada':'participantes de Manutenção Preventiva Realizada', 
  'Localização':'Localização', 
  'Localização Física no Estoque da Peça':'Localização Física no Estoque da Peça', 
  'Manutenção Preventiva Prevista (Cronograma)':'Manutenção Preventiva Prevista (Cronograma)', 
  'Cronograma de Manutenções Preventivas Realizadas':'Cronograma de Manutenções Preventivas Realizadas', 
  'Manutenção Preventiva Realizada (Tempos)':'Manutenção Preventiva Realizada (Tempos)', 
  'Tabela onde são apontados os Tempos de Manutenção Preventiva Realizada':'Tabela onde são apontados os Tempos de Manutenção Preventiva Realizada', 
  'Manutenções Preventivas Realizadas':'Manutenções Preventivas Realizadas', 
  'Esta Tela traz todas as Manutenções Preventivas Realizadas. Estes lançamentos são gerados pela tela de apontamento de Realizadas.':'Esta Tela traz todas as Manutenções Preventivas Realizadas. Estes lançamentos são gerados pela tela de apontamento de Realizadas.', 
  'Máquina':'Máquina', 
  'Máquina de Gabarito de Manutenção Preventiva':'Máquina de Gabarito de Manutenção Preventiva', 
  'Máquinas':'Máquinas', 
  'Nessa tela vamos cadastrar todas as máquinas da empresa, que estarão no roteiro e cronograma de Manutenções Preventivas e Corretivas':'Nessa tela vamos cadastrar todas as máquinas da empresa, que estarão no roteiro e cronograma de Manutenções Preventivas e Corretivas', 
  'MCA':'MCA', 
  'MENSAL':'MENSAL', 
  'MENSAL (ELE)':'MENSAL (ELE)', 
  'MENSAL (MEC)':'MENSAL (MEC)', 
  'Motivos de Espera':'Motivos de Espera', 
  'Qual é o motivo que pode atrasar a realização da Manutenção':'Qual é o motivo que pode atrasar a realização da Manutenção', 
  'MPO':'MPO', 
  'MPO (DIA/SEMANA/MES)':'MPO (DIA/SEMANA/MES)', 
  'Número':'Número', 
  'Número de Endereço':'Número de Endereço', 
  'Número da Nota Fiscal':'Número da Nota Fiscal', 
  'Número da Nota Fiscal emitida pelo usuario':'Número da Nota Fiscal emitida pelo usuario', 
  'Número de Série':'Número de Série', 
  'Número de Série da Máquina':'Número de Série da Máquina', 
  'Nome':'Nome', 
  'Nome da Peça':'Nome da Peça', 
  'Nota Fiscal de Entrada':'Nota Fiscal de Entrada', 
  'Nessa tela vamos cadastrar as Notas Fiscais de Entrada de Peças emitidas pelos usuarios, Nessa tela é incrementado o estoque de Peças na Empresa':'Nessa tela vamos cadastrar as Notas Fiscais de Entrada de Peças emitidas pelos usuarios, Nessa tela é incrementado o estoque de Peças na Empresa', 
  'Obrigatório Selecionar Subconjunto':'Obrigatório Selecionar Subconjunto', 
  'Especifica se a equipe e obrigada a selecionar o subconjunto (quando as máquinas forem subdividias em subconjuntos)':'Especifica se a equipe e obrigada a selecionar o subconjunto (quando as máquinas forem subdividias em subconjuntos)', 
  'Observações':'Observações', 
  'Comentários gerais sobre o usuario':'Comentários gerais sobre o usuario', 
  'Observações/Conclusão':'Observações/Conclusão', 
  'O Solicitante muda o status para concluído e descreve a conclusão':'O Solicitante muda o status para concluído e descreve a conclusão', 
  'Ociosa':'Ociosa', 
  'Esta máquina esta ociosa ou em funcionamento':'Esta máquina esta ociosa ou em funcionamento', 
  'Onde?':'Onde?', 
  'Onde foi o defeito na Máquina ou no SubConjunto':'Onde foi o defeito na Máquina ou no SubConjunto', 
  'País':'País', 
  'País do Endereço':'País do Endereço', 
  'Parou a Produção no Atendimento':'Parou a Produção no Atendimento', 
  'Parou a produção no Atendimento':'Parou a produção no Atendimento', 
  'Parou a Produção?':'Parou a Produção?', 
  'Está com a produção parada devida ao defeito que gerou a Manutenção Corretiva?':'Está com a produção parada devida ao defeito que gerou a Manutenção Corretiva?', 
  'Peça':'Peça', 
  'Peça Solicitada para o setor de Compras':'Peça Solicitada para o setor de Compras', 
  'Peça Nova':'Peça Nova', 
  'A peça adquira é nova ou reutilizada':'A peça adquira é nova ou reutilizada', 
  'Peças':'Peças', 
  'Aqui nos vamos cadastrar todas as peças usadas na manutenção corretiva dos equipamentos, através desse cadastro de peças iremos usar nos cadastro de Nota Fiscal, Pedidos de Peças, etc.':'Aqui nos vamos cadastrar todas as peças usadas na manutenção corretiva dos equipamentos, através desse cadastro de peças iremos usar nos cadastro de Nota Fiscal, Pedidos de Peças, etc.', 
  'Peço':'Peço', 
  'Preço da Peça qual foi comprado a peça':'Preço da Peça qual foi comprado a peça', 
  'Período':'Período', 
  'Periodicidade que vai ser aplicada a Manutenção Preventiva':'Periodicidade que vai ser aplicada a Manutenção Preventiva', 
  'Períodos M.P.':'Períodos M.P.', 
  'Nessa tela cadastramos os possíveis períodos que são feitas as Manutenções Preventivas':'Nessa tela cadastramos os possíveis períodos que são feitas as Manutenções Preventivas', 
  'Procedimento':'Procedimento', 
  'Procedimento a ser seguido':'Procedimento a ser seguido', 
  'QUADRIMESTRAL':'QUADRIMESTRAL', 
  'Quantidade':'Quantidade', 
  'Quantidade Solicitada':'Quantidade Solicitada', 
  'Que Fazer':'Que Fazer', 
  'Que Fazer no Item':'Que Fazer no Item', 
  'Requisição':'Requisição', 
  'Número da Requisição de Compra que gerou a Nota Fiscal de Peças':'Número da Requisição de Compra que gerou a Nota Fiscal de Peças', 
  'Requisições de Peças':'Requisições de Peças', 
  'Com esta tela podemos fazer as requisições de peças ao almoxarifado, reservando assim a peça no estoque para uso da manutenção corretiva do equipamento.':'Com esta tela podemos fazer as requisições de peças ao almoxarifado, reservando assim a peça no estoque para uso da manutenção corretiva do equipamento.', 
  'S.M.C. por Máquinas (Abertas x Encerradas) no Período':'S.M.C. por Máquinas (Abertas x Encerradas) no Período', 
  'Símbolo':'Símbolo', 
  'Qual símbolo (abreviação) deve ser associado ao Período':'Qual símbolo (abreviação) deve ser associado ao Período', 
  'SEMANAL':'SEMANAL', 
  'SEMANAL (ELE)':'SEMANAL (ELE)', 
  'SEMANAL (MEC)':'SEMANAL (MEC)', 
  'SEMESTRAL':'SEMESTRAL', 
  'SEMESTRAL (ELE)':'SEMESTRAL (ELE)', 
  'SEMESTRAL (MEC)':'SEMESTRAL (MEC)', 
  'SEMESTRAL (OPE)':'SEMESTRAL (OPE)', 
  'Sequência':'Sequência', 
  'Sequencia de participantes de Solicitação Compras':'Sequencia de participantes de Solicitação Compras', 
  'Sequência do Item':'Sequência do Item', 
  'Sequência do Item da Nota Fiscal de Entrada':'Sequência do Item da Nota Fiscal de Entrada', 
  'Setor':'Setor', 
  'Setor em que a máquina pertence':'Setor em que a máquina pertence', 
  'Setores':'Setores', 
  'Nessa tela vamos cadastrar os Setores da Empresa':'Nessa tela vamos cadastrar os Setores da Empresa', 
  //'SISTEMA GERENCIADOR DE MANUTENÇÕES':'SISTEMA GERENCIADOR DE MANUTENÇÕES', 
  'O agenda-esporte, SISTEMA GERENCIADOR DE MANUTENÇÕES, TRATA DA GERENCIA DAS MANUTENÇÕES PERIÓDICAS DOS EQUIPAMENTOS DENTRO DA EMPRESA, MANUTENÇÕES PREVENTIVAS/CORRETIVAS QUE SEGUE UM CRONOGRAMA DIÁRIOS, SEMANAL, MENSAL, TRIMESTRAL, QUADRIMESTRAL, SEMESTRAL E ANUAL. TENDO COMO BASE UM CHECKLIST PARA participantes ONDE É FEITO A CHECAGEM, REGISTRADO O TEMPO PREVISTO E REAL DE CADA ITEM E SUBITEM, CONTAMOS COM APONTAMENTOS DE TEMPO PARA CADA MANUTENÇÃO. TAMBÉM CONTAMOS COM O SUPORTE A CHAMADOS DE PARADAS DE MÁQUINAS, SOLICITAÇÃO DE MANUTENÇÕES E APONTAMENTOS DE TEMPOS JUNTO AOS MECÂNICOS. CONTROLE DE ESTOQUE DE PEÇAS E SOLICITAÇÕES DE PEÇAS E COMPRAS DE PEÇAS.':'O agenda-esporte, SISTEMA GERENCIADOR DE MANUTENÇÕES, TRATA DA GERENCIA DAS MANUTENÇÕES PERIÓDICAS DOS EQUIPAMENTOS DENTRO DA EMPRESA, MANUTENÇÕES PREVENTIVAS/CORRETIVAS QUE SEGUE UM CRONOGRAMA DIÁRIOS, SEMANAL, MENSAL, TRIMESTRAL, QUADRIMESTRAL, SEMESTRAL E ANUAL. TENDO COMO BASE UM CHECKLIST PARA participantes ONDE É FEITO A CHECAGEM, REGISTRADO O TEMPO PREVISTO E REAL DE CADA ITEM E SUBITEM, CONTAMOS COM APONTAMENTOS DE TEMPO PARA CADA MANUTENÇÃO. TAMBÉM CONTAMOS COM O SUPORTE A CHAMADOS DE PARADAS DE MÁQUINAS, SOLICITAÇÃO DE MANUTENÇÕES E APONTAMENTOS DE TEMPOS JUNTO AOS MECÂNICOS. CONTROLE DE ESTOQUE DE PEÇAS E SOLICITAÇÕES DE PEÇAS E COMPRAS DE PEÇAS.', 
  'Solicitação de Compras':'Solicitação de Compras', 
  'Nesta tela vamos cadastrar todas as solicitações de compras enviadas ao setor de compras pode ou não ser oriunda de uma Solicitação de Manutenção Corretiva':'Nesta tela vamos cadastrar todas as solicitações de compras enviadas ao setor de compras pode ou não ser oriunda de uma Solicitação de Manutenção Corretiva', 
  'Solicitação de Manutenção Corretiva':'Solicitação de Manutenção Corretiva', 
  'Solicitação ':'Solicitação ', 
  'Solicitações de Manutenção Corretiva':'Solicitações de Manutenção Corretiva', 
  'Nesta tela devemos cadastrar e trabalhar todos as solicitações de manutenção, pois de uma chamado de manutenção gera-se a Solicitação de Manutenção Corretiva quando efetivamente for necessário executar uma manutenção corretiva. Com esses registros podemos apontar tempos de manutenção, quais mecânicos estão trabalho na manutenção, tempos de horas trabalhadas e de hora parada de máquina, peças utilizadas na manutenção, requisições de peças ao almoxarifado. etc. ':'Nesta tela devemos cadastrar e trabalhar todos as solicitações de manutenção, pois de uma chamado de manutenção gera-se a Solicitação de Manutenção Corretiva quando efetivamente for necessário executar uma manutenção corretiva. Com esses registros podemos apontar tempos de manutenção, quais mecânicos estão trabalho na manutenção, tempos de horas trabalhadas e de hora parada de máquina, peças utilizadas na manutenção, requisições de peças ao almoxarifado. etc. ', 
  'Solicitante':'Solicitante', 
  'Usuário Solicitante  (Quem abriu o Chamado)':'Usuário Solicitante  (Quem abriu o Chamado)', 
  'Solução/Serviços':'Solução/Serviços', 
  'Descrição da Solução e Serviços executados':'Descrição da Solução e Serviços executados', 
  'Status':'Status', 
  'Status da Manutenção':'Status da Manutenção', 
  'Em que estágio anda a Manutenção Aberta, Iniciada, Em Andamento, Finalizada, etc.':'Em que estágio anda a Manutenção Aberta, Iniciada, Em Andamento, Finalizada, etc.', 
  'Status de S.M.C.':'Status de S.M.C.', 
  'SubConjunto':'SubConjunto', 
  'SubConjunto da Máquina':'SubConjunto da Máquina', 
  'SubTotal':'SubTotal', 
  'SubTotal do Item da Nota Fiscal':'SubTotal do Item da Nota Fiscal', 
  'Telefone':'Telefone', 
  'Telefone de Contato':'Telefone de Contato', 
  'Tempo':'Tempo', 
  'Tempo Calculado (minutos)':'Tempo Calculado (minutos)', 
  'Tempo Estimado (minutos)':'Tempo Estimado (minutos)', 
  'Tempo Estimado do Item em Minutos':'Tempo Estimado do Item em Minutos', 
  'Tempo Previsto':'Tempo Previsto', 
  'Tempo Previsto para conclusão da Manutenção':'Tempo Previsto para conclusão da Manutenção', 
  'Tempo Realizado (Minutos)':'Tempo Realizado (Minutos)', 
  'Tempo que realizou a Manutenção Preventiva':'Tempo que realizou a Manutenção Preventiva', 
  'Tempo Total':'Tempo Total', 
  'Tempo Total de Manutenção Preventiva para a Máquina':'Tempo Total de Manutenção Preventiva para a Máquina', 
  'Tipo de Manutenção':'Tipo de Manutenção', 
  'Tipo de Manutenção a ser aplicada na Solicitação':'Tipo de Manutenção a ser aplicada na Solicitação', 
  'Tipo Manutenção':'Tipo Manutenção', 
  'Equipe responsável pela M.P. e o Tipo de Manutenção Realizada':'Equipe responsável pela M.P. e o Tipo de Manutenção Realizada', 
  'Total':'Total', 
  'Valor Total da Nota Fiscal':'Valor Total da Nota Fiscal', 
  'Total Abertas':'Total Abertas', 
  'Total de S.M.C. por Máquina (Encerradas x Total ) no Período':'Total de S.M.C. por Máquina (Encerradas x Total ) no Período', 
  'Total de S.M.C. por Máquinas (Abertas x Total) no Período':'Total de S.M.C. por Máquinas (Abertas x Total) no Período', 
  'TRIMESTRAL':'TRIMESTRAL', 
  'TRIMESTRAL (ELE)':'TRIMESTRAL (ELE)', 
  'TRIMESTRAL (MEC)':'TRIMESTRAL (MEC)', 
  'TRIMESTRAL (OPE)':'TRIMESTRAL (OPE)', 
  'TTDPA':'TTDPA', 
  'TTMP':'TTMP', 
  'TTMP (ELE)':'TTMP (ELE)', 
  'TTMP (MEC)':'TTMP (MEC)', 
  'TTMP (MEC/ELE)':'TTMP (MEC/ELE)', 
  'Unidade':'Unidade', 
  'Unidade da Peça':'Unidade da Peça', 
};
